#!/usr/bin/env bash

set -euo pipefail

echo "🚀 Welcome to the Dotfiles installer!"
echo "-------------------------------------------------"
echo
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

#git clone --depth 1 git@github.com:Cenadros/Dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/install" self install
