#!/usr/bin/env bash

set -euo pipefail

echo "👉  Updating symlinks..."
cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "utils.bash"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

create_symlinks() {
    declare -a FILES_TO_SYMLINK=(
        ".aliases"
        ".exports"
        ".gitconfig"
        ".gitignore"
#        ".ssh/config"
        ".zlogin"
        ".zlogout"
        ".zpreztorc"
        ".zprofile"
        ".zshenv"
        ".zshrc"
    )

    local currentFile=""
    local sourceFile=""
    local targetFile=""
    local skipQuestions=false

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    skip_questions "$@" \
        && skipQuestions=true

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for currentFile in "${FILES_TO_SYMLINK[@]}"; do
        sourceFile="$(pwd)/$currentFile"
        targetFile="$HOME/$currentFile"

        if [ ! -e "$targetFile" ] || $skipQuestions; then
            execute \
                "ln -fs $sourceFile $targetFile" \
                "$targetFile → $sourceFile"
        elif [ "$(readlink "$targetFile")" == "$sourceFile" ]; then
            print_success "$targetFile → $sourceFile"
        else
            if ! $skipQuestions; then
                ask_for_confirmation "'$targetFile' already exists, do you want to overwrite it?"
                if answer_is_yes; then
                    rm -rf "$targetFile"

                    execute \
                        "ln -fs $sourceFile $targetFile" \
                        "$targetFile → $sourceFile"
                else
                    print_error "$targetFile → $sourceFile"
                fi
            fi
        fi
    done
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

main() {
    print_in_purple "\n • Create symbolic links\n\n"
    create_symlinks "$@"
}

main "$@"
