#!/bin/bash

export DOTFILES_PATH="$HOME/.dotfiles"

echo "👉  Copying wsl.conf file"
sudo cp "$DOTFILES_PATH/wsl.conf" /etc/wsl.conf

# Set up zsh as default shell
echo "👉  Changing default terminal to zsh"
chsh -s $(which zsh) > /dev/null


# Set up Docker
echo "👉  Installing docker"
case $(uname | tr '[:upper:]' '[:lower:]') in
  linux*)
    sudo apt-get update > /dev/null

    sudo apt-get install \
        ca-certificates \
        curl \
        gnupg \
        lsb-release -y > /dev/null

    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update > /dev/null
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y > /dev/null

    sudo groupadd docker
    sudo usermod -aG docker $USER
    ;;
  darwin*)
    # Download and install Docker for Mac
    curl -fsSL https://download.docker.com/mac/stable/Docker.dmg -o Docker.dmg
    open Docker.dmg
    cp -R /Volumes/Docker/Docker.app /Applications/
    rm Docker.dmg
    ;;
  *)
    echo "Please refer to the official documentation for your Operating System: https://docs.docker.com/desktop/"
    echo -n "Would you like to proceed with the next steps? (y/n)"
    read reply

    if [ "$reply" = n -o "$reply" = N ]
    then
       exit
    fi
    ;;
esac

echo "👉  Cloning prezto into: ${HOME}/.zprezto"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${HOME}/.zprezto" 2> /dev/null || git -C "${HOME}/.zprezto" pull

echo "👉  Cloning prezto-contrib into: ${HOME}/.zprezto/contrib"
git clone --recurse-submodules https://github.com/belak/prezto-contrib "${HOME}/.zprezto/contrib" 2> /dev/null || git -C "${HOME}/.zprezto/contrib" pull

echo "👉  Cloning nvm into: ${HOME}/.nvm"
git clone https://github.com/nvm-sh/nvm.git "${HOME}/.nvm" 2> /dev/null || git -C "${HOME}/.nvm" checkout `git -C "${HOME}/.nvm" describe --abbrev=0 --tags --match "v[0-9]*" $(git -C "${HOME}/.nvm" rev-list --tags --max-count=1)`

echo "👉  Checking nvm latest version"
pushd ${HOME}/.nvm
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
popd

echo "👉  Installing brew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo '# Set PATH, MANPATH, etc., for Homebrew.' >> ${HOME}/.zprofile
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ${HOME}/.zprofile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
sudo apt-get install build-essential -Y

echo "👉  Installing mkcert"
brew install mkcert

echo "👉  Generating mkcert certificates"
mkcert -install
mkcert -CAROOT

echo "👉  Installing make"
sudo apt install make -Y

echo "👉  Git config"
read -p "Type in your mail for gitconfig: " input
sed -i "s/test@test.com/$input/g" ${DOTFILES_PATH}/dotfiles/.gitconfig

read -p "Type in your name for gitconfig: " input
sed -i "s/test/$input/g" ${DOTFILES_PATH}/dotfiles/.gitconfig

echo "👉  Symlinks"
bash "$DOTFILES_PATH/scripts/symlinks"

echo "👉  A system reboot is required to apply all changes"
echo -n "Would you like to proceed right now? (y/n)"
read reply

if [ "$reply" = y -o "$reply" = Y ]
then
   sudo reboot
else
   echo "Don't forget to restart your computer manually."
fi
