#!/bin/bash
set -e

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "utils.bash"

OS="$(get_os)"

echo "🚀 Updating Dotfiles"
echo "-------------------------------------------------"
echo

echo "👉  Updating dotfiles repository..."
pushd "${HOME}/.dotfiles" > /dev/null
git pull
popd > /dev/null

if [ -d "${HOME}/.zprezto" ]; then
    echo "👉  Updating prezto repository..."
    pushd "${HOME}/.zprezto" > /dev/null
    git pull && git submodule update --init --recursive
    popd > /dev/null
fi

if [ -d "${HOME}/.nvm" ]; then
    echo "👉  Updating nvm repository..."
    pushd "${HOME}/.nvm" > /dev/null
    git fetch --tags origin && git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
    popd > /dev/null
fi

echo "👉  Updating Homebrew..."
init_brew
if cmd_exists brew; then
    brew update && brew upgrade
fi

# Re-link Karabiner config (macOS)
if [ "$OS" = "macos" ] && [ -f "${HOME}/.dotfiles/config/karabiner/karabiner.json" ]; then
    echo "👉  Linking Karabiner-Elements configuration"
    mkdir -p "$HOME/.config/karabiner"
    ln -fs "${HOME}/.dotfiles/config/karabiner/karabiner.json" "$HOME/.config/karabiner/karabiner.json"
fi

bash "$HOME/.dotfiles/scripts/symlinks"

echo ""
echo "✅  Update complete!"
